apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver-deploy
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 5
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: hello-go:v5.6
          imagePullPolicy: IfNotPresent

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 2
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 10

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/files"
              name: volume-lorem
              readOnly: true

      volumes:
        - name: volume-lorem
          configMap:
            name: configmap-lorem
            items:
              - key: conteudo
                path: "lorem.txt"
