apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver-deploy
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: hello-go:v5.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - mountPath: "/go/files"
              name: volume-lorem
              readOnly: true
      volumes:
        - name: volume-lorem
          configMap:
            name: configmap-lorem
            items:
              - key: conteudo
                path: "lorem.txt"
