apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver-deploy
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 5
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: hello-go:v3
          imagePullPolicy: IfNotPresent
          env:
            - name: NAME
              value: "rafaelmuto"
            - name: AGE
              value: "36"
