apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver-replicaset
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: hello-go:latest
          imagePullPolicy: IfNotPresent
